### ISSUE TITLE
Exclude heading from block count to insert ad

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/super-cool-ad-inserter-plugin#69] opened 2021-11-04 10:39 UTC
Currently, ad insertion in post is configured by settings 

- Number of blocks before first insertion
- Number of blocks between insertions

This method also count H1-H6 headings as separate block. It's better to exclude H1-H6 headings from block count or change configuration settings to 

- Number of paragraphs before first insertion
- Number of paragraphs between insertions

**Comment by earcos** [comment] 2021-11-05 01:27
It also should exclude elements like images or blockquotes or cites imho.

**Comment by yogeshbeniwal** [comment] 2021-11-05 01:49
@earcos Yeah changing configuration settings to count only <p> element should be able to take care of all other blocks.

**Comment by adekbadek** [comment] 2021-11-05 13:43
What's the goal here? 
Asking because there was a - maybe - [similar issue](https://github.com/Automattic/newspack-popups/issues/555) with heading in another plugin which inserts stuff in-content. The problem was that the stuff was inserted e.g. right after a heading or a floated image. Is this about that?

**Comment by earcos** [comment] 2021-11-05 13:47
The goal is that ads are only inserted between paragraphs, instead of between headings and text or headings and images or between images or quotes.

**Comment by adekbadek** [comment] 2021-11-05 14:31
Got it. In the following post structure there would be no ad inserted at all, then. Isn't the goal to have ads inserted only _after_ paragraphs? 

```
heading
paragraph
image
paragraph
quote
paragraph
```

**Comment by yogeshbeniwal** [comment] 2021-11-05 14:56
@adekbadek If i am able to understand other referenced issue, this is little different. 

Currently ads are inserted on basis of block count. In this case for post which contain large number of H1-H6 heading, quotes and other smaller blocks, for readers ads seems to be quite a lot, though its configured to be inserted at every 4th block. With same settings its ok for post with more number of paragraphs.

I suggest, we count only `<p>` for interval to insert ads, rather than all blocks.

**Comment by earcos** [comment] 2021-11-05 16:41
@yogeshbeniwal correct 😊

**Comment by adekbadek** [comment] 2021-11-08 10:08
> I suggest, we count only <p> for interval to insert ads, rather than all blocks.

That's proposed in #74 👌

**Comment by miguelpeixe** [comment] 2021-11-09 21:30
[v0.5.0](https://github.com/Automattic/super-cool-ad-inserter-plugin/releases/tag/v0.5.0) was released with #74 and other bugfixes (#75) related to the new block-based ad insertion. Please verify if this fixes the unexpected behavior.

**Comment by yogeshbeniwal** [comment] 2021-11-10 00:55
@miguelpeixe Thanks it now counts only `<p>`. However it waits for next paragraph after count for ad insertion, which lead to ad insertion at

`<p>`
`<p>`
`<p>`
`<p>`
`<h>` or any combination of consecutive  non `<p>` block
[Ad]
`<p>`

than

`<p>`
`<p>`
`<p>`
`<p>`
[Ad]
`<h>` or any combination of consecutive  non `<p>` block
`<p>`

**Comment by miguelpeixe** [comment] 2021-11-12 20:50
Good catch! I was able to identify why this is happening and #78 should fix it.

**Closed** 2021-11-16 13:40 UTC
